FROM centos

RUN yum -y install openssh-server
RUN useradd remote_user && \
    echo "12345678" | passwd remote_user --stdin && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh

COPY remote-key.pub /home/remote_user/.ssh/authorized_keys
RUN chown remote_user:remote_user -R /home/remote_user/.ssh && \
    chmod 600 /home/remote_user/.ssh/authorized_keys
RUN /usr/sbin/sshd-keygen

RUN yum install -y mysql
RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    pip install awscli --upgrade

RUN yum install -y mc

CMD /usr/sbin/sshd -D
