version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "/home/mint-2/Документы/COURSES/jenkins-FromZeroToHero/jenkins-data/jenkins_home:/var/jenkins_home"
    networks:
      - net
networks:
  net: